### ISSUE TITLE
Review OpenAPI editors

### ISSUE THREAD

**Issue by xylix** [apinf/open-api-designer#119]
There are other editors (e.g. [OpenAPI-GUI](https://openapi-gui.herokuapp.com/), [Apicurio](http://www.apicur.io/)) for creating API descriptions compatible with the OpenAPI spec. We should review them and find their pros and cons .

We are doing this because we are considering helping out another project instead of developing open-api-designer. This should let us reach our goals faster, because right now the same things are being coded in multiple projects.

**Comment by tulir** [comment]
### OpenAPI-GUI
Pros:
* OpenAPI 3.0 support
* All necessary forms finished

Cons:
* The form UI is inconsistent in some places

This comment can be edited as new pros or cons are found.

**Comment by tulir** [comment]
### Apicurio
Pros:
* All necessary forms are available

Cons:
* 

Other:
* Licensed under [Apache 2.0](https://github.com/Apicurio/apicurio-studio/blob/master/LICENSE) which may or may not be a problem.

This comment can be edited as new pros or cons are found.

**Comment by tulir** [comment]
### OpenAPI-GUI ([3.0](https://openapi-gui.herokuapp.com/))
Pros:
* Supports OpenAPI 3.0

Cons:
* The form UI is inconsistent in some places
* Some forms are missing, but not as much as OpenAPI designer
* The spec isn't automatically saved (even locally)
* Not developed as actively as others

Other: (TODO)

This comment can be edited as new pros or cons are found.

**Comment by tulir** [comment]
### Open API designer
Pros:
* The code is familiar to us
* We have full control over everything (branding, design choices, etc..)
* Follows the OpenAPI spec closely, which makes it nicer to use for people who know the spec.

Cons:
* Some critical forms are missing
* No OpenAPI 3.0 support

Other:
* Nothing, yet

This comment can be edited as new pros or cons are found.

**Comment by tulir** [comment]
### Conclusions

TODO

**Comment by tulir** [comment]
## Conclusions
The other editors don't have any very significant advantages over our editor. The main advantage is a usable 
Reading and understanding the code of other editors would take a while, which could nullify the time-related benefits of contributing to other editors instead of developing our own.

**Comment by tulir** [comment]
## Conclusions
The other editors don't have any very significant advantages over our editor. The main advantage is that they already have everything needed to make real OpenAPI documents, while we're still missing some things in the Paths section.
However, reading and understanding the code of other editors would take a while, which could nullify the time-related benefits of contributing to other editors instead of developing our own.

**Comment by tulir** [comment]
We might want to think about #91 before making a decision here. Having a clear goal would make it easier to figure out if the other editors are sufficiently close to our goal.

@brylie @bajiat Opinions?

**Comment by brylie** [comment]
One pro, in my opinion, of our OpenAPI Designer is that the UI framework is oriented towards web standards, specifically WebComponents. We also chose the Aurelia framework because it is 'batteries included', offering many features including routing, i18n, two-way data binding, CLI, etc.

Related to framework discussion, the OpenAPI UI is using Vue.js. The Vue.js code seems to be relatively cleanly separated and easy to understand, in a similar way to Aurelia.

**Comment by brylie** [comment]
Another consideration:

In my opinion, not having a JSON preview may not be a *con*. In effect, the JSON preview may be unnecessary, from an end-user standpoint, since the user just needs to design the OpenAPI file in a humane manner. While JSON and YAML are humane, e.g. when compared with XML, our user interface is intended to be much more simple, self-documenting, and intuitive for humans. JSON and YAML are still, IMO, machine languages.

**Comment by brylie** [comment]
I propose that after about one more day of consideration/discussion, we vote for a preferred solution. We can use the heart feedback on the relevant comment. E.g. if you like option A, add a heart to that comment. Lets limit our hearts to two each, so this is kind of like a dot vote.

**Comment by xylix** [comment]
I did some time estimations on how much time it would take for me and Tulir to implement the functionality in our scope in these four editors.

# Time estimates

## Generic
* For implementing OpenAPI 3.0 support in any editor that doesn’t have it yet, we’ll need to learn the spec [1-2 days]
* Figuring out what needs to be validated and how [2 days]

## OpenAPI-GUI 2.0/3.0 (bootstrap)
* We’ll need to learn Vue.js, it’ll slow us down in the beginning
* Probably less upstream support than with the buefy version.
* Validation [4 days]
* I18n implementation [2 days]

## Apicurio:

* Getting used to angular2, maven will take some time (we might even want to get rid of maven altogether, but then we will lose some upstream compatibility) [2 days]
* Github saving needs to be made optional, integration with apinf platform will probably take longer than with other solutions.

Right now apicurio is still pretty buggy. It is in beta, so upstream will probably be fixing bugs over time. We think it would be really hard to develop apicurio compared to the other alternatives.

##OpenAPI-GUI 3.0 (buefy):
* We’ll need to learn Vue.js, it’ll slow us down in the beginning
* Some sections are missing (not sure which of those are required because we don’t know OpenAPI 3 yet)
* Implementing 2.0 support will take long, maybe longer than implementing 3.0 support in Open API designer. [5-15 days]
* UI inconsistency and bugfixes, testing needs to be done [10 days]
* Validation [4 days]
* I18n implementation [2 days]

## Open API designer:

* OpenAPI 2.0 required functionality [5 days]

* 3.0 support [3-12 days, depends on the required changes]
* Validation [2 days]
* I18n implementation [1 day]

**Comment by xylix** [comment]
Mine and Tulir's conclusion:

We think, looking at our goals, that the most efficient solution is to go on developing Open API designer.

**Comment by bajiat** [comment]
Looking at the estimates given I would agree with you that continuing with Open API designer is a good option. I appreciate that you have taken into account the necessity to support both 2.0 and 3.0.

I hope however that you have learnt from the comparison having taken a look at the other available solutions. 

I agree with @brylie that json preview is not mandatory. Or there could be an option to toggle the preview on and off.

**Comment by xylix** [comment]
I am closing this issue now that the conclusion has been made and accepted.

Discussion about the JSON preview can continue at #92.
