### ISSUE TITLE
After adding a scheme, the action buttons disappears unless mouse is hovered on the scheme section. Also there are multiple instances of the same action pane appearing for each scheme field

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#15]
http://g.recordit.co/lPDFztDn4Q.gif

**Comment by Xylix** [comment]
The action panes are not same. Every new action pane corresponds to it's own field. This is useful because it allows the action pane to be used for moving fields up and down, and it can be used for removing fields. But it is true that it looks a little bloated. If it is a problem, open a new issue for it. 

I made the toolbar/action pane sticky now (#01f930e).
