### ISSUE TITLE
Make 0.1.0 release

### ISSUE THREAD

**Issue by brylie** [apinf/open-api-designer#18]
We should make an initial release soon. As a convention, our releases should follow [semantic versioning](http://semver.org/). The 0.1.0 release can be made against the current master, or at a previous commit.

**Comment by brylie** [comment]
Ping @bajiat @tulir @Xylix

**Comment by xylix** [comment]
@bylie @bajiat  A release draft has been made, could you review it?

**Comment by bajiat** [comment]
@xylix Hi, I would suggest that you change the title of the release to 0.1.0 instead of "Initial release"

It does not have to a pre-release, if you are confident that the SW is functional.

Also, consider writing a release note. Here is the format I use in APInf releases:

# New
* followed by a bulleted list of new features
  
# Improved
* followed by a bulleted list of improved features (since last release) - you can leave this out from the initial release

# Contributors
* First name Last name (@Github name)

**Comment by xylix** [comment]
I updated the draft. Is it good now, or should we describe the new features in more detail?

**Comment by bajiat** [comment]
I quess "a form based editor for creating Open API Specifications" is what the whole app does, not just the content of first release.

Maybe you could say
* Initial form created (maybe you can list some of the fields)
* JSON preview

**Comment by xylix** [comment]
Release has now been published.
