### ISSUE TITLE
Create wireframe for overall application design structure

### ISSUE THREAD

**Issue by brylie** [apinf/open-api-designer#3]
We are currently designing the application incrementally, without discussing how the overall UI should look. Wireframes are a good way to explore options for the UI layout, because they are simple to create and throw away.

Start sketching a few UI wireframes, to explore possible designs.

**Comment by Nazarah** [comment]
Interested

**Comment by Nazarah** [comment]
@xylix @tulir 
am adding primary sketches of the open API page.
The page has a title and shows the swagger version used as hardcoded
The editor is divided into 8 sections: Info, Schemes, Consumes, Produces, Path, Security, Tags and External documentation.
The sections are displayed on top of the editor and json preview window.
You can browse through the editors by clicking on the sections or using Previous and Next Buttons bellow the editor.
The editor and json preview window have info icons to describe what they are for and how to use them.
The JSON preview would show all the contents written, but would highlight the portion indicating where in the editor the user is right now. (e.g. if the user is editing a path, json preview would show the code of the path editor highlighted.)
You can save the content anytime by clicking Save button and download the json file/
![1info](https://cloud.githubusercontent.com/assets/17976243/20743654/434cb9c8-b6e0-11e6-9af5-714a9d5ab7ed.png)
 
Open questions: Since Path may have sections like Schemes, Consumes, and produces, is there any way to show the additional subsections in the GUI?

**Comment by Nazarah** [comment]
Rest of the wireframes are here:
![2schemes](https://cloud.githubusercontent.com/assets/17976243/20744144/ca4668b4-b6e2-11e6-8595-142760b30b85.png)
![3consumes](https://cloud.githubusercontent.com/assets/17976243/20744145/ca4bc840-b6e2-11e6-8a79-e64dc86f3b23.png)
![4produces](https://cloud.githubusercontent.com/assets/17976243/20744146/ca4df80e-b6e2-11e6-9e70-e3e80c0ed4b1.png)
![5paths](https://cloud.githubusercontent.com/assets/17976243/20744149/ca573036-b6e2-11e6-8d57-efa78826ed2b.png)
![6security](https://cloud.githubusercontent.com/assets/17976243/20744147/ca50e38e-b6e2-11e6-8a1a-da6aa1b4ea13.png)
![7tags](https://cloud.githubusercontent.com/assets/17976243/20744148/ca540f82-b6e2-11e6-961f-0431f00d7d07.png)
![8externaldocument](https://cloud.githubusercontent.com/assets/17976243/20744150/ca61ff5c-b6e2-11e6-865a-602484b02539.png)

**Comment by Nazarah** [comment]
@tulir @xylix I have one design in my mind
![1info2](https://cloud.githubusercontent.com/assets/17976243/20786041/4cdc943c-b7ac-11e6-914c-234855683020.png)
Here the sections appear as the 1st column in the view.
And for sections (e.g. paths) where you can add additional subsections (e.g. schemes, consumes, etc.) the added subsections can appear dynamically in the that column.
User's location in the editor would be highlighted there.
The rest of the functionalities work as the same as described in the upper comments.

Please let me know about your feedback.

**Comment by xylix** [comment]
@Nazarah What do you think about using varying sizes to show subfielding? I think this would help with cases like paths, where the user might want to input even dozens of paths. 
![screenshot from 2016-12-01 10-19-38](https://cloud.githubusercontent.com/assets/13387304/20786608/b624720e-b7af-11e6-9d60-0ccd928c50e6.png)

I think the latest design you posted looks pretty good. We'll build a couple of demos today.

**Comment by tulir** [comment]
I implemented something that slightly resembles the first wireframe in the ui1 branch.

**Comment by tulir** [comment]
I made a pull request for the ui1 branch #20
